---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: main-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/foodStorage/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: food-storage
  labels:
    app: food-storage
spec:
  volumes:
  - name: pv-storage
    persistentVolumeClaim:
      claimName: volume-claim
  containers:
  - name: restful
    image: foodstorage
    imagePullPolicy: Never
    ports:
    - containerPort: 8080
    volumeMounts:
    - mountPath: "/"
      name: pv-storage

---
apiVersion: v1
kind: Service
metadata:
  name: port-forwarder
  labels:
    app: port-forwarder
spec:
  type: NodePort
  selector:
    app: food-storage
  ports:
  - name: http
    protocol: TCP
    targetPort: 8080
    port: 80
    nodePort: 30001