---
apiVersion: v1
kind: Pod
metadata:
  name: food-storage
  labels:
    app: food-storage
spec:
  containers:
  - name: restful
    image: foodstorage
    imagePullPolicy: Never
    ports:
    - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: port-forwarder
  labels:
    app: port-forwarder
spec:
  type: NodePort
  selector:
    app: food-storage
  ports:
  - name: http
    protocol: TCP
    targetPort: 8080
    port: 80
    nodePort: 30001